AddCSLuaFile()
SWEP.Base = "weapon_zn_base_cs16"
SWEP.PrintName = "CS 1.6 M249"
SWEP.ViewModel = "models/weapons/cs16/c_m249.mdl"
SWEP.WorldModel = "models/weapons/cs16/player/p_m249.mdl"
SWEP.HoldType = "ar2"
SWEP.Slot = 2
SWEP.FirePresentation = "rifle556"
SWEP.Primary.Automatic = true
SWEP.Primary.ClipSize = 256
SWEP.BulletDamage = 18
SWEP.BulletSpread = 0.04
SWEP.FireDelay = 0.1
SWEP.BaseClipSize = 100
SWEP.ReloadTime = 4.5
SWEP.GoreSeverFactor = 1.1
SWEP.BulletForce = 4
SWEP.RecoilPitch = 1
SWEP.FireSound = "zombiesim/cs16/weapons/m249-1.wav"
SWEP.ReloadSound = "zombiesim/cs16/weapons/m249_coverup.wav"
SWEP.ReloadFinishSound = "zombiesim/cs16/weapons/m249_coverdown.wav"
