AddCSLuaFile()
SWEP.Base = "weapon_zn_base_cs16"
SWEP.PrintName = "CS 1.6 AK-47"
SWEP.ViewModel = "models/weapons/cs16/c_ak47.mdl"
SWEP.WorldModel = "models/weapons/cs16/player/p_ak47.mdl"
SWEP.HoldType = "ar2"
SWEP.Slot = 2
SWEP.FirePresentation = "rifle762"
SWEP.Primary.Automatic = true
SWEP.BulletDamage = 22
SWEP.BulletRange = 4096
SWEP.BulletSpread = 0.03
SWEP.FireDelay = 0.11
SWEP.BaseClipSize = 30
SWEP.ReloadTime = 2.5
SWEP.GoreSeverFactor = 1.3
SWEP.BulletForce = 5
SWEP.RecoilPitch = 0.95
SWEP.RecoilYaw = 0.45
SWEP.MuzzleBlastSpeed = 110
SWEP.FireSound = "zombiesim/cs16/weapons/ak47-1.wav"
SWEP.ReloadSound = "zombiesim/cs16/weapons/ak47_clipout.wav"
SWEP.ReloadFinishSound = "zombiesim/cs16/weapons/ak47_boltpull.wav"
