AddCSLuaFile()
SWEP.Base = "weapon_zn_base_cs16"
SWEP.PrintName = "CS 1.6 M3"
SWEP.ViewModel = "models/weapons/cs16/c_m3.mdl"
SWEP.WorldModel = "models/weapons/cs16/player/p_m3.mdl"
SWEP.IdleSequence = "idle"
SWEP.ReloadSequence = "insert"
SWEP.HoldType = "shotgun"
SWEP.Slot = 3
SWEP.FirePresentation = "shotgun"
SWEP.BulletCount = 9
SWEP.BulletDamage = 9
SWEP.BulletRange = 1800
SWEP.BulletSpread = 0.075
SWEP.FireDelay = 0.85
SWEP.BaseClipSize = 8
SWEP.ReloadTime = 2.5
SWEP.GoreSeverFactor = 2.5
SWEP.BulletForce = 3
SWEP.RecoilPitch = 1.8
SWEP.MuzzleBlastSpeed = 120
SWEP.FireSound = "zombiesim/cs16/weapons/m3-1.wav"
SWEP.ReloadSound = "zombiesim/cs16/weapons/m3_insertshell.wav"
SWEP.ReloadFinishSound = "zombiesim/cs16/weapons/m3_pump.wav"
SWEP.CycleSound = "zombiesim/cs16/weapons/m3_pump.wav"
SWEP.CycleSoundDelay = 0.3
