AddCSLuaFile()
SWEP.Base = "weapon_zn_base_cs16"
SWEP.PrintName = "CS 1.6 Scout"
SWEP.ViewModel = "models/weapons/cs16/c_scout.mdl"
SWEP.WorldModel = "models/weapons/cs16/player/p_scout.mdl"
SWEP.FireSequence = "shoot_1"
SWEP.HoldType = "ar2"
SWEP.Slot = 4
SWEP.FirePresentation = "sniper762"
SWEP.BulletDamage = 48
SWEP.BulletRange = 6144
SWEP.BulletSpread = 0.006
SWEP.FireDelay = 0.95
SWEP.BaseClipSize = 10
SWEP.ReloadTime = 2.4
SWEP.GoreSeverFactor = 1.8
SWEP.BulletForce = 6
SWEP.RecoilPitch = 1.6
SWEP.FireSound = "zombiesim/cs16/weapons/scout_fire-1.wav"
SWEP.ReloadSound = "zombiesim/cs16/weapons/scout_clipout.wav"
SWEP.ReloadFinishSound = "zombiesim/cs16/weapons/scout_bolt.wav"
SWEP.CycleSound = "zombiesim/cs16/weapons/scout_bolt.wav"
SWEP.CycleSoundDelay = 0.4
