AddCSLuaFile()
SWEP.Base = "weapon_zn_base_cs16"
SWEP.PrintName = "CS 1.6 Galil"
SWEP.ViewModel = "models/weapons/cs16/c_galil.mdl"
SWEP.WorldModel = "models/weapons/cs16/player/p_galil.mdl"
SWEP.IdleSequence = "idle"
SWEP.HoldType = "ar2"
SWEP.Slot = 2
SWEP.FirePresentation = "rifle556"
SWEP.Primary.Automatic = true
SWEP.BulletDamage = 19
SWEP.BulletSpread = 0.03
SWEP.FireDelay = 0.11
SWEP.BaseClipSize = 35
SWEP.ReloadTime = 2.6
SWEP.GoreSeverFactor = 1.1
SWEP.FireSound = "zombiesim/cs16/weapons/galil-1.wav"
SWEP.ReloadSound = "zombiesim/cs16/weapons/galil_clipout.wav"
SWEP.ReloadFinishSound = "zombiesim/cs16/weapons/galil_boltpull.wav"
